# Generated by Django 4.0.5 on 2022-09-24 09:39

from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=500)),
                ('crime_location', models.TextField(blank=True)),
                ('prof', models.ImageField(blank=True, null=True, upload_to=report.models.upload_to, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
